databaseChangeLog:
  - changeSet:
      id: 2024_03_26_0009_create_settings_table
      author: Timothy Karani
      changes:
        - createTable:
            tableName: settings
            columns:
              - column:
                  name: id
                  type: "INT UNSIGNED"
                  autoIncrement: true
                  constraints:
                    nullable: false
                    primaryKey: true
              - column:
                  name: key
                  type: VARCHAR(100)
                  constraints:
                    nullable: true
              - column:
                  name: value
                  type: TEXT
                  constraints:
                    nullable: true
              - column:
                  name: created_at
                  type: TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: updated_at
                  type: TIMESTAMP
                  constraints:
                    nullable: false
              - column:
                  name: deleted_at
                  type: TIMESTAMP
                  constraints:
                    nullable: true